server:
  port: 8080

spring:
    application:
        name: migration-core
    messages:
        basename: messages/message
        encoding: UTF-8
    datasource:
        url:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username:
        password:
    jpa:
        # open-in-view: false
        # generate-ddl: false
        show-sql: true
        # hibernate:
        #  ddl-auto: validate
        database-platform: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  paths-to-match:
    - /v1/backup/**
    - /v1/resource/**
    - /v1/restore/**
    - /v1/migration/**

  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    groups-order: desc
    operations-sorter: method